#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-numerizer
Version  : 0.2.0
Release  : 3
URL      : https://rubygems.org/downloads/numerizer-0.2.0.gem
Source0  : https://rubygems.org/downloads/numerizer-0.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= Numerizer
Numerizer is a gem to help with parsing numbers in natural language from strings (ex forty two). It was extracted from the awesome Chronic gem http://github.com/evaryont/chronic.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n numerizer-0.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-numerizer.gemspec

%build
gem build rubygem-numerizer.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
numerizer-0.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/numerizer-0.2.0 && rake --trace test && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/numerizer-0.2.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/numerizer-0.2.0/ri/Numerizer/andition-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/numerizer-0.2.0/ri/Numerizer/cdesc-Numerizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/numerizer-0.2.0/ri/Numerizer/numerize-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/numerizer-0.2.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/numerizer-0.2.0/ri/page-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/numerizer-0.2.0/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/numerizer-0.2.0/.document
/usr/lib64/ruby/gems/2.2.0/gems/numerizer-0.2.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/numerizer-0.2.0/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/numerizer-0.2.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/numerizer-0.2.0/VERSION
/usr/lib64/ruby/gems/2.2.0/gems/numerizer-0.2.0/lib/numerizer.rb
/usr/lib64/ruby/gems/2.2.0/gems/numerizer-0.2.0/numerizer.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/numerizer-0.2.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/numerizer-0.2.0/test/test_numerizer.rb
/usr/lib64/ruby/gems/2.2.0/specifications/numerizer-0.2.0.gemspec
